# Generated by Django 4.0 on 2021-12-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=101)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, default='default.png', upload_to='%Y/%m/%d/')),
            ],
        ),
    ]
