# Generated by Django 4.0 on 2021-12-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nipadapp', '0002_cuustomer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuustomer',
            new_name='Customer',
        ),
    ]
